services:
  - type: web
    name: pneumonia-detector
    env: python
    buildCommand: ""
    startCommand: gunicorn app.app:app
    runtime: python
    region: singapore
    plan: free
    autoDeploy: true
    branch: main
